Update pipeline react-native

diff --git a/.harness/reactnative.yaml b/.harness/reactnative.yaml
--- a/.harness/reactnative.yaml
+++ b/.harness/reactnative.yaml
@@ -470,7 +470,11 @@ pipeline:
                           export BUILD_THREADS=2
 
 
-
+                                      # Skip yarn install on metro bump commits as the package is not yet
+                                      # available on npm
+                                      if [[ $(echo "$GIT_COMMIT_DESC" | grep -c "Bump metro@") -eq 0 ]]; then
+                                        yarn install --non-interactive --cache-folder ~/.cache/yarn
+                                      fi
 
 
 
@@ -525,6 +529,179 @@ pipeline:
                         sourcePaths:
                           - /home/ubuntu/.cache/yarn
                         archiveFormat: Tar
+                  - step:
+                      type: Run
+                      name: Download Dependencies Using Buck
+                      identifier: Download_Dependencies_Using_Buck
+                      spec:
+                        shell: Sh
+                        command: ./scripts/circleci/buck_fetch.sh
+                  - step:
+                      type: Run
+                      name: Build Test React Native using Buck
+                      identifier: Build_Test_React_Native_using_Buck
+                      spec:
+                        shell: Sh
+                        command: |2-
+                                      buck build ReactAndroid/src/main/java/com/facebook/react
+                                      buck build ReactAndroid/src/main/java/com/facebook/react/shell
+                  - step:
+                      type: Run
+                      name: Run Tests - Android Unit Tests with Buck
+                      identifier: Run_Tests_Android_Unit_Tests_with_Buck
+                      spec:
+                        shell: Sh
+                        command: buck test ReactAndroid/src/test/... --config build.threads=$BUILD_THREADS --xml ./reports/buck/all-results-raw.xml
+                  - step:
+                      type: Run
+                      name: Build JavaScript Bundle for instrumentation tests
+                      identifier: Build_JavaScript_Bundle_for_instrumentation_tests
+                      spec:
+                        shell: Sh
+                        command: node cli.js bundle --max-workers 2 --platform android --dev true --entry-file ReactAndroid/src/androidTest/js/TestBundle.js --bundle-output ReactAndroid/src/androidTest/assets/AndroidTestBundle.js
+                  - step:
+                      type: Run
+                      name: Build Tests - Android Instrumentation Tests with Buck
+                      identifier: Build_Tests_Android_Instrumentation_Tests_with_Buck
+                      spec:
+                        shell: Sh
+                        command: |2
+                                      if [[ ! -e ReactAndroid/src/androidTest/assets/AndroidTestBundle.js ]]; then
+                                        echo "JavaScript bundle missing, cannot run instrumentation tests. Verify Build JavaScript Bundle step completed successfully."; exit 1;
+                                      fi
+                                      source scripts/android-setup.sh && NO_BUCKD=1 scripts/retry3 timeout 300 buck build ReactAndroid/src/androidTest/buck-runner:instrumentation-tests --config build.threads=$BUILD_THREADS
+                  - step:
+                      type: Run
+                      name: Collect test results
+                      identifier: Collect_test_results
+                      spec:
+                        shell: Sh
+                        command: |2-
+                                      find . -type f -regex ".*/build/test-results/debug/.*xml" -exec cp {} ./reports/build/ \;
+                                      find . -type f -regex ".*/outputs/androidTest-results/connected/.*xml" -exec cp {} ./reports/outputs/ \;
+                                      find . -type f -regex ".*/buck-out/gen/ReactAndroid/src/test/.*/.*xml" -exec cp {} ./reports/buck/ \;
+                                      if [ -f ~/react-native/reports/buck/all-results-raw.xml ]; then
+                                        ~/react-native/scripts/circleci/buckToJunit/buckToJunit.sh ~/react-native/reports/buck/all-results-raw.xml ~/react-native/reports/junit/results.xml
+                                      fi
+                        reports:
+                          type: JUnit
+                          spec:
+                            paths:
+                              - ./reports/junit/
+              sharedPaths:
+                - /home/ubuntu/.cache/yarn
+        - stage:
+            name: test_android
+            identifier: test_android
+            type: CI
+            spec:
+              cloneCodebase: true
+              platform:
+                os: Linux
+                arch: Amd64
+              runtime:
+                type: Cloud
+                spec: {}
+              execution:
+                steps:
+                  - parallel:
+                      - step:
+                          type: RestoreCacheGCS
+                          name: "restore yarn cache "
+                          identifier: restore_yarn_cache
+                          spec:
+                            connectorRef: ronakgcpbucket
+                            bucket: migration-artifact-comman
+                            key: v5-yarn-cache-test_android-{{ arch }}-{{ checksum "yarn.lock" }}
+                            archiveFormat: Tar
+                          when:
+                            stageStatus: Success
+                          failureStrategies:
+                            - onFailure:
+                                errors:
+                                  - AllErrors
+                                action:
+                                  type: Ignore
+                      - step:
+                          type: RestoreCacheGCS
+                          name: Restore Cache gradel
+                          identifier: Restore_Cache_gradel
+                          spec:
+                            connectorRef: ronakgcpbucket
+                            bucket: migration-artifact-comman
+                            key: v1-gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "ReactAndroid/gradle.properties" }}
+                            archiveFormat: Tar
+                          failureStrategies:
+                            - onFailure:
+                                errors:
+                                  - AllErrors
+                                action:
+                                  type: Ignore
+                  - step:
+                      type: Run
+                      name: install yarn
+                      identifier: install_yarn
+                      spec:
+                        connectorRef: account.harnessImage
+                        image: reactnativecommunity/react-native-android:6.2
+                        shell: Sh
+                        command: |+
+                          export CIRCLE_SHA1="c19548728c9be3ecc91e6fefb35bc14929109d60"
+
+                          export GIT_COMMIT_DESC="git log --format=oneline -n 1 c19548728c9be3ecc91e6fefb35bc14929109d60"
+                                # The public github tokens are publicly visible by design
+                          export PUBLIC_PULLBOT_GITHUB_TOKEN_A="a6edf8e8d40ce4e8b11a"
+                          export PUBLIC_PULLBOT_GITHUB_TOKEN_B="150e1341f4dd9c944d2a"
+                          export PUBLIC_ANALYSISBOT_GITHUB_TOKEN_A="312d354b5c36f082cfe9"
+                          export PUBLIC_ANALYSISBOT_GITHUB_TOKEN_B="07973d757026bdd9f196"
+                          export HOMEBREW_NO_AUTO_UPDATE=1
+
+                          export KOTLIN_HOME="third-party/kotlin"
+
+
+                          #  image: reactnativecommunity/react-native-android:6.2
+
+                          export TERM="dumb"
+                          export ADB_INSTALL_TIMEOUT=10
+                          export GRADLE_OPTS='-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
+                          export BUILD_THREADS=2
+
+
+                                      # Skip yarn install on metro bump commits as the package is not yet
+                                      # available on npm
+                                      if [[ $(echo "$GIT_COMMIT_DESC" | grep -c "Bump metro@") -eq 0 ]]; then
+                                        yarn install --non-interactive --cache-folder ~/.cache/yarn
+                                      fi
+
+
+
+                          #download_gradle_dependencies
+
+                  - parallel:
+                      - step:
+                          type: SaveCacheGCS
+                          name: save yarn cache
+                          identifier: save_yarn_cache
+                          spec:
+                            connectorRef: ronakgcpbucket
+                            bucket: migration-artifact-comman
+                            key: v5-yarn-cache-test_android-{{ arch }}-{{ checksum "yarn.lock" }}
+                            sourcePaths:
+                              - /home/ubuntu/.cache/yarn
+                            archiveFormat: Tar
+                      - step:
+                          type: SaveCacheGCS
+                          name: Save Cache gradel
+                          identifier: Save_Cache_gradel
+                          spec:
+                            connectorRef: ronakgcpbucket
+                            bucket: migration-artifact-comman
+                            key: v1-gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "ReactAndroid/gradle.properties" }}
+                            sourcePaths:
+                              - /home/ubuntu/.gradle
+                              - ReactAndroid/build/downloads
+                              - ReactAndroid/build/third-party-ndk
+                            archiveFormat: Tar
                   - step:
                       type: Run
                       name: Download Dependencies Using Buck
